module.exports = {
  arrowParens: 'always',
  arrowParens: 'always',
  bracketLine: false,
  bracketSpacing: true,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'consistent',
  semi: true,
  singleQuote: true,
  tabs: false,
  tabWidth: 2,
  trailingComma: 'es5',
};
